---
name: Actions CI

'on': [push, pull_request]

jobs:
  build_and_test:
    name: integer-encoding-rs
    strategy:
      fail-fast: false
      matrix:
        features: ["tokio_async", "futures_async", ""]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: cargo check
        run: |
          cargo check --no-default-features --features=${{ matrix.features }}

      - name: cargo test
        run: |
          cargo test --no-default-features --features=${{ matrix.features }}
